modLoader="javafml"
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="The MIT License (MIT)"
issueTrackerURL="https://github.com/onVoid/Adjunct/issues"
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]]
modId="adjunct"
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
# ${file.jarVersion} will substitute the value of the Implementation-Version as read from the mod's JAR file metadata
# see the associated build.gradle script for how to populate this completely automatically during a build
version="0.1.0"
displayName="Adjunct"
# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
updateJSONURL="http://onvoid.net/adjunct/update.json"
# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
logoFile="adjunct.png"
credits="Thanks Vazkii for variant Quark block code and models."
authors="onVoid"
description='''
Additions you need.
'''

[[dependencies.adjunct]]
    modId="quark"
    mandatory=false
    versionRange="[r2.4,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.adjunct]]
    modId="thermal"
    mandatory=false
    versionRange="[1.3.2,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.adjunct]]
    modId="create"
    mandatory=false
    versionRange="[v0.3.2d,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.adjunct]]
    modId="forge"
    mandatory=true
    versionRange="[35.1.28,)"
    ordering="AFTER"
    side="BOTH"